title:  web dev course
author: Narayan
email: narayansoni854@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Assignment website as a part of web devlopment course by microsoft

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
